name: Rust CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
    - name: Build
      run: make build
    - name: Format
      run: make format
    - name: Lint
      run: make lint
    #- name: Run Tests
      #run: make test
    - name: Setup DB
      run: make setup
    - name: Insert to DB
      run: make insert
    - name: Query from DB
      run: make query
    - name: Update in DB
      run: make update
    - name: Delete from DB
      run: make delete
